---
- name: Deploy Web App
  hosts: n2
  become: yes

  tasks:
  - name: Install git
    yum:
      name: git
      state: present

  - name: Host code
    git:
      repo: https://github.com/ManLikeLight/ansible-work-5.git
      dest: /var/www/html    

      

...